---
title: "Day 3 - Conditionals & Loops"
author: "Erica Dale"
date: "2022-08-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(palmerpenguins)
```

### `if` statements
back-ticks create code-style appearance

```{r}
burrito <- 2.8

if (burrito > 2) {
  print("I love burritos!")
}
```

#### Example with strings,  using a string match

```{r}
my_ships <- c("Millenium Falcon", "X-wing", "Tie-Fighter", "Death Star")

str_detect(my_ships, pattern = "r")
str_detect(my_ships, pattern = "x") # case sensitive

# Looks within each element, and TRUE/FALSE does this pattern display in any element
# What's actually in a phrase?

phrase <- "I love burritos"
if (str_detect(phrase, "love")) {
  print("I am a burrito fan.")
}
```


#### Example of `%in%` operator

```{r}
view(starwars) # dplyr dataset starwars

tatooine_characters <- starwars |> 
  filter(homeworld == "Tatooine")
view(tatooine_characters)

# Use the %in% operator to check for multiple positive matches, shortcut for "or" statements
tatooine_endor_naboo <- starwars |> 
  filter(homeworld %in% c("Tatooine", "Naboo", "Endor"))
```


### `if-else` statement
```{r}
pika <- 89.1

if(pika > 60) {
  print("mega pika")
} else {
  print("normal pika")
}
```

```{r}
marmot <- 2.8
if(marmot < 0.5) {
  print("this is a small marmot")
} else if (marmot >= 0.5 & marmot < 3) {
  print("this is a medium marmot")
} else {
  print("this is a big marmot")
}
```


### Summary table
#### `group_by() %>% summarize()`
Can use this to make pivot tables

```{r}
view(penguins)

unique(penguins$species) # returns the unique values only, does not group
unique(starwars$eye_color)

penguins |> 
  group_by(species, island) |>   # Organizing column by different species
  summarize(mean_bill_length = mean(bill_length_mm, na.rm = TRUE),
            sd_bill_length = sd(bill_length_mm, na.rm = TRUE),
            n = n()) # the count of each BUT includes NA items ignored above
# Output table has species with subgroups of islands, then data on mean and sd 
```

```{r}
# Find the mean and sd of character height in `starwars` grouped by homeworld

starwars |> 
  group_by(homeworld) |> 
  summarize(height_mean = mean(height, na.rm = TRUE),
            heigh_sd = sd(height, na.rm = TRUE),
            n = n())

# Find maximum and min flipper length, sample size, for each species and gender of penguins
penguins |> 
  group_by(species, sex) |> 
  summarize(max_flipper = max(flipper_length_mm, na.rm = TRUE),
            min_flipper = min(flipper_length_mm, na.rm = TRUE),
            n = n())

```

